name: Deploy WinShirt Plugin via SFTP (Clean + Upload)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SFTP Clean Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean remote plugin directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            rm -rf Winshirt/wp-content/plugins/winshirt-plugin/*

      - name: Upload plugin via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          source: "."
          target: "Winshirt/wp-content/plugins/winshirt-plugin"
          strip_components: 0
