name: Deploy WinShirt Plugin via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: "/Winshirt/wp-content/plugins/winshirt"
          protocol: sftp
          strip_components: 0
